### ISSUE TITLE
don't get anything by running test.py, how to generate the wav?

### ISSUE THREAD

**Issue by azraelkuan** [barronalex/Tacotron#14]
hi, i am new to tts.
when i run the test.py, i only get a dir, weightes/arctic/tacotron, but in the dir , there is nothing in it.
so i want to know how can i generate the wav from the text???

**Comment by mrelich** [comment]
Hello,

You have to first train a model and then you can test it.  At the moment, I don't believe there is a default model given with this package.  Right now, it stores the audio file as a tensor, which you can see in the `log` directory unter `log/<datasetname>/tacotron/test/`.  I'm not super familiar with how to view them, but I've been using tensorboard and pointing the `logdir` for tensorboard to `log` directory.

Alternatively, you can edit the code to dump the wave files.  Edit this line: https://github.com/barronalex/Tacotron/blob/master/test.py#L60
You add at the end of the method a filename.  See the function call here: https://github.com/barronalex/Tacotron/blob/master/audio.py#L56

One thing I am struggling with is understanding why the output during training is somewhat audible, but when I run the same text through the testing script (test.py) it is total garbage... If I can't figure that out soon I will post another issue.

**Comment by barronalex** [comment]
You can now run 'download_weights.sh' then 'test.py' and generate audio from pre-trained weights without downloading the data.
