### ISSUE TITLE
loss exploded

### ISSUE THREAD

**Issue by YisenWang** [barronalex/Tacotron#7]
Does anyone run into this issue ?  In the training process, "loss exploded" threw out and the training is stopped.

**Comment by candlewill** [comment]
Yes. I decreased the learning rate, and then restored training.

**Comment by YisenWang** [comment]
@candlewill how large is your lr?

**Comment by candlewill** [comment]
0.001, 0.0005, 0.0003, 0.0001, 0.00005, ...
