### ISSUE TITLE
Test won't generate speech used in training while training does generate correctly.

### ISSUE THREAD

**Issue by onyedikilo** [barronalex/Tacotron#9]
I tired to generate a wav file after training for a day using test.py but the result was mostly noise no speech.

I used the same words as in the training data. It correctly renders speech while training, but using the same phrase for test.py results in just noise.

Anyone have any idea what might be the cause of it?

**Comment by lifeiteng** [comment]
What's the training dataset size?

2017-06-20 21:36 GMT+08:00 Kaan Bey <notifications@github.com>:

**Comment by onyedikilo** [comment]
@lifeiteng , doesn't the test.py just restore the network and send the input phrases from a text file and generate an output? train.py does the same thing but the outputs don't match while the inputs are the same (the input text). So what has this got to do with the data size? Shouldn't the outputs be the same since the network and the inputs are the same? 

Btw the data I use has 1900 phrases around 1.5hrs speech.

**Comment by ljun4121** [comment]
In evaluation, unlike training, the output of the decoder fed back into the decoder input of next time step, so the result can be different.
